# Workflow to test-run data when we modify JowilderExtractor.
name: Jo Wilder Exporter CI Test
on:
  push:
    paths:
    - 'games/JOWILDER/**'
    - '.github/workflows/jowilder.yml'
  workflow_dispatch: # Allow manual trigger of this workflow from the Actions tab
jobs:
  JoWilder_CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get OpenConnect
      run: sudo apt-get -q update && sudo apt-get -q install openconnect
    - name: Connect VPN
      run: echo ${{ secrets.VPN_PASS }} | sudo openconnect --protocol=gp -u ${{ secrets.VPN_USER }} --passwd-on-stdin soe.vpn.wisc.edu &
    - name: Get Dependencies
      uses: ./.github/actions/OGD_dependencies
    - name: Set up Config File
      uses: ./.github/actions/OGD_config
      with:
        vpn_user: ${{secrets.VPN_USER}}
        vpn_pass: ${{secrets.VPN_PASS}}
        sql_host: ${{secrets.SQL_HOST}}
        sql_user: ${{secrets.SQL_USER}}
        sql_pass: ${{secrets.SQL_PASS}}
        # TODO: set log_level to DEBUG once we've made sure there aren't excess outputs from the extractor itself.
        log_level: "INFO"
    - name: Do Export of yesterday's data
      uses: ./.github/actions/export_yesterday
      with:
        game: JOWILDER
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./*.log
    - name: Upload zips as artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./data/JOWILDER/*.zip
