# This is a basic workflow to help you get started with Actions

name: OpenGameData - Automated Exports

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "monthly_export"
  monthly_export:
    # The type of runner that the job will run on
    name: Export Monthly Data - Crystal
    runs-on: ubuntu-latest

    # Steps to get set up for an export
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Get OpenConnect
      run: sudo add-apt-repository ppa:phusen/openconnect && sudo apt-get update && sudo apt-get install openconnect
    - name: Connect VPN
      run: echo ${{ secrets.VPN_PASS }} | sudo openconnect --protocol=gp -u ${{ secrets.VPN_USER }} --passwd-on-stdin soe.vpn.wisc.edu &
    - name: Clone code
      uses: actions/checkout@v2
    - name: Set up code
      run: cp config.py.template config.py 
    - name: Set SSH hostname
      run: sed -i 's/hostname/${{secrets.SSH_HOST}}/g' config.py
    - name: Set SSH username
      run: sed -i 's/WCER AD User/${{secrets.VPN_USER}}/g' config.py
    - name: Set SSH password
      run: sed -i 's/WCER AD Password/${{secrets.VPN_PASS}}/g' config.py
    - name: Set SQL username
      run: sed -i 's/username/${{secrets.SQL_USER}}/g' config.py
    - name: Set SQL password
      run: sed -i 's/password/${{secrets.SQL_PASS}}/g' config.py
    - run: ls
    - run: pwd
