# Workflow to test-run data when we modify CrystalExtractor.
name: Test running conditionals.
on:
  workflow_dispatch: # Allow manual trigger of this workflow from the Actions tab
    inputs:
      game:
        description: "The games to be exported, comma-separated"
        required: true
        default: "JOWILDER"
      monthly:
        description: "The conditional"
        required: true
        default: false
jobs:
  test_export:
    name: Export Game
    runs-on: ubuntu-latest
    strategy:
      matrix:
        game: ${{ FromJson(github.event.inputs.game) }}
      fail-fast: false # we don't want to cancel just because one game fails.
      max-parallel: 1

    steps:
    - name: Do Export of Month
      if: github.event.inputs.monthly == 'true'
      run: echo Did it!
    - name: Do Export of Range
      if: github.event.inputs.monthly != 'true'
      run: echo Did not do it!